CREATE TABLE public.customers (
  customer_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  user_id UUID NULL,
  email TEXT NOT NULL,
  CONSTRAINT customers_pkey PRIMARY KEY (customer_id)
);

CREATE TABLE public.vendors (
  vendor_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name TEXT NOT NULL,
  description TEXT NULL,
  email TEXT NULL,
  web_site TEXT NULL,
  CONSTRAINT vendors_pkey PRIMARY KEY (vendor_id)
);

CREATE TABLE public.products (
  product_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  product_name TEXT NOT NULL,
  price NUMERIC(10, 2) NULL,
  in_stock INTEGER NULL,
  vendor_id BIGINT NULL,
  image_url TEXT NULL,
  CONSTRAINT products_pkey PRIMARY KEY (product_id),
  CONSTRAINT products_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES vendors (vendor_id)
);

CREATE TABLE public.orders (
  order_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  customer_id BIGINT NOT NULL,
  order_date TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
  user_id uuid NULL DEFAULT AUTH.UID (),
  CONSTRAINT orders_pkey PRIMARY KEY (order_id),
  CONSTRAINT orders_customer_fkey FOREIGN KEY (customer_id) REFERENCES public.customers (customer_id)
);

CREATE TABLE public.order_details (
  order_detail_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  order_id BIGINT NOT NULL,
  product_id BIGINT NOT NULL,
  quantity INTEGER NULL,
  cost NUMERIC(10, 2) NULL,
  CONSTRAINT order_details_pkey PRIMARY KEY (order_detail_id),
  CONSTRAINT order_details_order_fkey FOREIGN KEY (order_id) REFERENCES public.orders (order_id),
  CONSTRAINT order_details_product_fkey FOREIGN KEY (product_id) REFERENCES public.products (product_id)
);